# Generated by Django 4.2.3 on 2023-08-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_1app', '0002_alter_record_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
