# Generated by Django 4.2.3 on 2023-08-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_1app', '0003_alter_record_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='Area_Pin_Code',
        ),
    ]
